# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ccfcfa33f8f9d936f161c02cfaae27dd7b69fd5238c564af6cfb16e150b917dcd6378f687440227fcb0129a9617de4ef723b8fe4b990e9ca866aa956f88baa

test:
  secret_key_base: 4b62d63882dbfe3a11276c24867c2bdf7e86e84a153c366b3bf98e342ec3878adfa4e463f618d55dc4a786d3b273430dfa24e7eaeb6bc16b8134b2803ac6b25b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
